### ISSUE TITLE
When python train.py，There‘s an error about hydra？

### ISSUE THREAD

**Issue by Jolinbaby** [kakaobrain/flame#10]
I change my hydra version to 1.1，
Successfully installed antlr4-python3-runtime-4.8 hydra-core-1.1.0 omegaconf-2.1.2

then i run python train.py，the error information is as follows：

[2023-02-17 17:04:46,332][src.training_pipeline][INFO] - Instantiating datamodule <src.datamodules.humanml3d_datamodule.HumanML3DDataModule>
[2023-02-17 17:04:46,415][numexpr.utils][INFO] - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2023-02-17 17:04:46,415][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2023-02-17 17:04:46,584][src.training_pipeline][INFO] - Instantiating model <src.models.diffusion_module.DiffusionLitModule>
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\osmesa.py", line 22, in GL
    return ctypesloader.loadLibrary(
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\ProgramData\Anaconda3\envs\flame\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 575, in _locate
    import_module(mod)
  File "D:\ProgramData\Anaconda3\envs\flame\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\A-project\flame\flame\src\models\diffusion_module.py", line 29, in <module>
    from src.utils.vis_util import render_video_summary
  File "D:\A-project\flame\flame\src\utils\vis_util.py", line 14, in <module>
    from body_visualizer.mesh.mesh_viewer import MeshViewer
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\body_visualizer\mesh\mesh_viewer.py", line 30, in <module>
    import pyrender
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\osmesa.py", line 66, in GetCurrentContext
    function = self.OSMesa.OSMesaGetCurrentContext
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\osmesa.py", line 60, in OSMesa
    def OSMesa( self ): return self.GL
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\OpenGL\platform\osmesa.py", line 28, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    main()
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\main.py", line 49, in decorated_main
    _run_hydra(
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 367, in _run_hydra
    run_and_report(
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 214, in run_and_report
    raise ex
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\hydra.py", line 110, in run
    _ = ret.return_value
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\core\utils.py", line 233, in return_value
    raise self._return_value
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\core\utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 22, in main
    return train(config)
  File "D:\A-project\flame\flame\src\training_pipeline.py", line 48, in train
    model: LightningModule = hydra.utils.instantiate(config.model)
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 240, in instantiate_node
    target = _resolve_target(node.get(_Keys.TARGET))

  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 104, in _resolve_target
    return _locate(target)
  File "D:\ProgramData\Anaconda3\envs\flame\lib\site-packages\hydra\_internal\utils.py", line 577, in _locate
    raise ImportError(
ImportError: Encountered error: `('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)` when loading module 'src.models.diffusion_module.DiffusionLitModule'
<img width="1380" alt="截屏2023-02-17 17 05 52" src="https://user-images.githubusercontent.com/60809535/219601099-812f4b5f-bbee-4dcd-baac-2b8aac1ddcdd.png">

**Comment by jihoonerd** [comment]
It seems the error comes from the graphics library. Can you try it after installing the following packages?
```
apt install libboost-dev libglfw3-dev libgles2-mesa-dev freeglut3-dev libosmesa6-dev libgl1-mesa-glx 

```
